POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1bm55QDEyMyIsImlkIjoiNjVlYWNiN2U4ZTdkNzI3ZDQxNzU4MzhjIiwiaWF0IjoxNzA5OTExMzA3fQ.Dmx7anUBfHgbddVnLfb6nv68cIilyZg1OynQFd6L8kA

{
    "title": "chapter",
    "author": "ramesh",
    "url": "google.com",
    "likes": 25,
    "user": "65eacb7e8e7d727d4175838c"
}

